### ISSUE TITLE
Update python3

### ISSUE THREAD

**Issue by jasonb5** [CDAT/xmgrace#2]
Code was never updated for python 3.

- [ ] Update code from python 2 to 3
- [ ] Build new conda package

**Comment by arulalant** [comment]
Hai,

conda install -c cdat xmgrace

After installing xmgrace inside cdat8.2.1 via conda, it gives following error.

Python 3.8.6 | packaged by conda-forge | (default, Dec 26 2020, 04:50:20) 
[Clang 11.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import xmgrace
>>> x=xmgrace.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/arulalan/miniconda3/envs/cdat8.2.1/lib/python3.8/site-packages/xmgrace/xmgrace.py", line 2678, in __init__
    self._start_pipe(xmgrace_args)
  File "/Users/arulalan/miniconda3/envs/cdat8.2.1/lib/python3.8/site-packages/xmgrace/xmgrace.py", line 2765, in _start_pipe
    self.pipe = os.fdopen(fd_w, 'w', 0)
  File "/Users/arulalan/miniconda3/envs/cdat8.2.1/lib/python3.8/os.py", line 1023, in fdopen
    return io.open(fd, *args, **kwargs)
ValueError: can't have unbuffered text I/O
>>> Descriptor 25 not open for reading

How should I overcome out of this error ?

Thanks.

**Comment by arulalant** [comment]
I am getting the same error for python 3.7 as well. @jasonb5

**Comment by jasonb5** [comment]
@arulalant I'll look into this error.

**Comment by arulalant** [comment]
Hai,
I installed xmgrace via conda inside cdat8.2.1 (today) as shown below and got the following error while invoking it.
This is for kind information. Thanks.

$ conda install -c conda-forge -c cdat xmgrace
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/arulalan/miniconda3/envs/cdat8.2.1

  added / updated specs:
    - xmgrace


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    xmgrace-8.1.0              |0_h1234567_ge4fc737          28 KB  cdat
    ------------------------------------------------------------
                                           Total:          28 KB

The following NEW packages will be INSTALLED:

  xmgrace            cdat/noarch::xmgrace-8.1.0-0_h1234567_ge4fc737
Proceed ([y]/n)? y
Downloading and Extracting Packages
xmgrace-8.1.0        | 28 KB     | ######################################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(cdat8.2.1) Arulalans-MacBook-Pro:~ arulalan$ python
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:57:50) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import xmgrace
>>> x=xmgrace.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/arulalan/miniconda3/envs/cdat8.2.1/lib/python3.7/site-packages/xmgrace/xmgrace.py", line 2678, in __init__
    self._start_pipe(xmgrace_args)
  File "/Users/arulalan/miniconda3/envs/cdat8.2.1/lib/python3.7/site-packages/xmgrace/xmgrace.py", line 2765, in _start_pipe
    self.pipe = os.fdopen(fd_w, 'w', 0)
  File "/Users/arulalan/miniconda3/envs/cdat8.2.1/lib/python3.7/os.py", line 1029, in fdopen
    return io.open(fd, *args, **kwargs)
ValueError: can't have unbuffered text I/O
>>> Descriptor 22 not open for reading

I hope it will be resolved in the next update/upgrade of cdat.
Thanks,
